# Generated by Django 4.0.6 on 2022-08-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("cron_expression", models.CharField(max_length=32)),
                ("is_inactive", models.BooleanField(default=False)),
                ("service_id", models.CharField(max_length=64, null=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
